config/routes.rb
Rails.application.routes.draw do

  resources :magic_parts

  resources :pearls

  resources :battles

  get 'item/index'

  devise_for :users, :controllers => { registrations: 'registrations_' }
  get 'home/index'

  root 'home#index'
  post 'worlds/generate_new_area' => "worlds#generate_new_area"
  post 'worlds/claim_area' => "worlds#claim_area"
  post 'worlds/attack' => "worlds#attack"
  post 'battles/escape' => "battles#escape"
  post 'battles/join' => "battles#join"
  post 'worlds/search_location' => "worlds#search_location"
  post 'worlds/collect_world_item' => "worlds#collect_world_item"
  post 'worlds/teleport' => "worlds#get_teleport"
  get 'worlds/teleport' => "worlds#teleport"
  post 'item/item_action' => "item#item_action"
  resources :characters do
    resource :items
  end
  resources :worlds
  resources :guide
  resources :item
  resources :npc
  resources :lock
  resources :inventory do
    resources :items
  end

  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
  end

end

app/models/battle.rb
class Battle < ActiveRecord::Base
end

app/models/biome.rb
class Biome < ActiveRecord::Base
end

app/models/caves.rb
class Caves < ActiveRecord::Base
end

app/models/character.rb
class Character < ActiveRecord::Base
  validates_uniqueness_of :LastName
  belongs_to :user
  belongs_to :charclass
  belongs_to :race
  has_many :inventories
end

app/models/construction.rb
class Construction < ActiveRecord::Base
end

app/models/dungeons.rb
class Dungeons < ActiveRecord::Base
end

app/models/guide.rb
class Guide < ActiveRecord::Base
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  has_many :items, dependent: :destroy
  belongs_to :character
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :inventory
  has_many :inventories
  has_many :pearls
end

app/models/key.rb
class Key < ActiveRecord::Base
end

app/models/lock.rb
class Lock < ActiveRecord::Base
end

app/models/magic_part.rb
class MagicPart < ActiveRecord::Base
  self.inheritance_column = nil
end

app/models/material.rb
class Material < ActiveRecord::Base
end

app/models/npc.rb
class Npc < ActiveRecord::Base
end

app/models/pearl.rb
class Pearl < ActiveRecord::Base
  belongs_to :item
  self.inheritance_column = nil
end

app/models/trade.rb
class Trade < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :characters, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/world.rb
class World < ActiveRecord::Base
  validates :title, presence: true,
            length: { minimum: 5 }
end

app/controllers/magic_parts_controller.rb
class MagicPartsController < ApplicationController
  before_action :set_magic_part, only: [:show, :edit, :update, :destroy]

  # GET /magic_parts
  # GET /magic_parts.json
  def index
    if current_user.try(:admin?)
      @magic_parts = MagicPart.all
    else
      redirect_to("/")
    end
  end

  # GET /magic_parts/1
  # GET /magic_parts/1.json
  def show
  end

  # GET /magic_parts/new
  def new
    if current_user.try(:admin?)
      @magic_part = MagicPart.new
    else
      redirect_to("/")
    end
  end

  # GET /magic_parts/1/edit
  def edit
  end

  # POST /magic_parts
  # POST /magic_parts.json
  def create
    @magic_part = MagicPart.new(magic_part_params)

    respond_to do |format|
      if @magic_part.save
        format.html { redirect_to @magic_part, notice: 'Magic part was successfully created.' }
        format.json { render :show, status: :created, location: @magic_part }
      else
        format.html { render :new }
        format.json { render json: @magic_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magic_parts/1
  # PATCH/PUT /magic_parts/1.json
  def update
    respond_to do |format|
      if @magic_part.update(magic_part_params)
        format.html { redirect_to @magic_part, notice: 'Magic part was successfully updated.' }
        format.json { render :show, status: :ok, location: @magic_part }
      else
        format.html { render :edit }
        format.json { render json: @magic_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magic_parts/1
  # DELETE /magic_parts/1.json
  def destroy
    @magic_part.destroy
    respond_to do |format|
      format.html { redirect_to magic_parts_url, notice: 'Magic part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_magic_part
      @magic_part = MagicPart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def magic_part_params
      params.require(:magic_part).permit(:title, :type, :effect)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/magic_parts_helper.rb
module MagicPartsHelper
end

app/helpers/npc_helper.rb
module NpcHelper
end

app/views/magic_parts/_form.html.erb
<% content_for :javascripts  do %>
    <script src="/assets/magic_parts.js.coffee?body=1"></script>
<% end %>
<%= form_for(@magic_part) do |f| %>
  <% if @magic_part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@magic_part.errors.count, "error") %> prohibited this magic_part from being saved:</h2>

      <ul>
      <% @magic_part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.select :type, options_for_select([["None", "none"],["Target", "target"],["Damage", "damage"],["Effect", "effect"],["Trigger","trigger"]])%>
  </div>
    <div id="selected">

    </div>
  <div class="field">
    <%= f.label :effect %><br>
    <%= f.text_field :effect %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/magic_parts/edit.html.erb
<h1>Editing magic_part</h1>

<%= render 'form' %>

<%= link_to 'Show', @magic_part %> |
<%= link_to 'Back', magic_parts_path %>

app/views/magic_parts/index.html.erb
<h1>Listing magic_parts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Type</th>
      <th>Effect</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @magic_parts.each do |magic_part| %>
      <tr>
        <td><%= magic_part.title %></td>
        <td><%= magic_part.type %></td>
        <td><%= magic_part.effect %></td>
        <td><%= link_to 'Show', magic_part %></td>
        <td><%= link_to 'Edit', edit_magic_part_path(magic_part) %></td>
        <td><%= link_to 'Destroy', magic_part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Magic part', new_magic_part_path %>

app/views/magic_parts/new.html.erb
<h1>New magic_part</h1>

<%= render 'form' %>

<%= link_to 'Back', magic_parts_path %>

app/views/magic_parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @magic_part.title %>
</p>

<p>
  <strong>Type:</strong>
  <%= @magic_part.type %>
</p>

<p>
  <strong>Effect:</strong>
  <%= @magic_part.effect %>
</p>

<%= link_to 'Edit', edit_magic_part_path(@magic_part) %> |
<%= link_to 'Back', magic_parts_path %>