config/routes.rb
Rails.application.routes.draw do

  resources :magic_parts

  resources :pearls

  resources :battles

  get 'item/index'

  devise_for :users, :controllers => { registrations: 'registrations_' }
  get 'home/index'

  root 'home#index'
  post 'worlds/generate_new_area' => "worlds#generate_new_area"
  post 'worlds/claim_area' => "worlds#claim_area"
  post 'worlds/attack' => "worlds#attack"
  post 'battles/escape' => "battles#escape"
  post 'battles/join' => "battles#join"
  post 'worlds/search_location' => "worlds#search_location"
  post 'worlds/collect_world_item' => "worlds#collect_world_item"
  post 'worlds/teleport' => "worlds#get_teleport"
  get 'worlds/teleport' => "worlds#teleport"
  post 'item/item_action' => "item#item_action"
  resources :characters do
    resource :items
  end
  resources :worlds
  resources :guide
  resources :item
  resources :npc
  resources :lock
  resources :inventory do
    resources :items
  end

  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
  end

end

app/models/battle.rb
class Battle < ActiveRecord::Base
end

app/models/biome.rb
class Biome < ActiveRecord::Base
end

app/models/caves.rb
class Caves < ActiveRecord::Base
end

app/models/character.rb
class Character < ActiveRecord::Base
  validates_uniqueness_of :LastName
  belongs_to :user
  belongs_to :charclass
  belongs_to :race
  has_many :inventories
end

app/models/construction.rb
class Construction < ActiveRecord::Base
end

app/models/dungeons.rb
class Dungeons < ActiveRecord::Base
end

app/models/guide.rb
class Guide < ActiveRecord::Base
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  has_many :items, dependent: :destroy
  belongs_to :character
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :inventory
  has_many :inventories
  has_many :pearls
end

app/models/key.rb
class Key < ActiveRecord::Base
end

app/models/lock.rb
class Lock < ActiveRecord::Base
end

app/models/magic_part.rb
class MagicPart < ActiveRecord::Base
  self.inheritance_column = nil
end

app/models/material.rb
class Material < ActiveRecord::Base
end

app/models/npc.rb
class Npc < ActiveRecord::Base
end

app/models/pearl.rb
class Pearl < ActiveRecord::Base
  belongs_to :item
  self.inheritance_column = nil
end

app/models/trade.rb
class Trade < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :characters, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/world.rb
class World < ActiveRecord::Base
  validates :title, presence: true,
            length: { minimum: 5 }
end

app/controllers/pearls_controller.rb
class PearlsController < ApplicationController
  before_action :set_pearl, only: [:show, :edit, :update, :destroy]

  # GET /pearls
  # GET /pearls.json
  def index
    @pearls = Pearl.all
  end

  # GET /pearls/1
  # GET /pearls/1.json
  def show
  end

  # GET /pearls/new
  def new
    @pearl = Pearl.new
  end

  # GET /pearls/1/edit
  def edit
  end

  # POST /pearls
  # POST /pearls.json
  def create
    @pearl = Pearl.new(pearl_params)

    respond_to do |format|
      if @pearl.save
        format.html { redirect_to @pearl, notice: 'Pearl was successfully created.' }
        format.json { render :show, status: :created, location: @pearl }
      else
        format.html { render :new }
        format.json { render json: @pearl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pearls/1
  # PATCH/PUT /pearls/1.json
  def update
    respond_to do |format|
      if @pearl.update(pearl_params)
        format.html { redirect_to @pearl, notice: 'Pearl was successfully updated.' }
        format.json { render :show, status: :ok, location: @pearl }
      else
        format.html { render :edit }
        format.json { render json: @pearl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pearls/1
  # DELETE /pearls/1.json
  def destroy
    @pearl.destroy
    respond_to do |format|
      format.html { redirect_to pearls_url, notice: 'Pearl was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pearl
      @pearl = Pearl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pearl_params
      params.require(:pearl).permit(:title, :parts, :type, :ep, :effect, :item_id)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/npc_helper.rb
module NpcHelper
end

app/helpers/pearls_helper.rb
module PearlsHelper
end

app/views/pearls/_form.html.erb
<% content_for :javascripts  do %>
    <script src="/assets/pearls.js.coffee?body=1"></script>
<% end %>
<%= form_for(@pearl) do |f| %>
  <% if @pearl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pearl.errors.count, "error") %> prohibited this pearl from being saved:</h2>

      <ul>
      <% @pearl.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :parts %><br>
    <%= f.text_field :parts %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.select :type, options_for_select([["None", "none"],["Target", "target"],["Self", "self"],["Area of Effect", "aoe"],["Team","team"]])%>
  </div>
    <div id="selected">

    </div>
  <div class="field">
    <%= f.label :ep %><br>
    <%= f.number_field :ep %>
  </div>
  <div class="field">
    <%= f.label :effect %><br>
    <%= f.text_field :effect %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.text_field :item_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pearls/edit.html.erb
<h1>Editing pearl</h1>

<%= render 'form' %>

<%= link_to 'Show', @pearl %> |
<%= link_to 'Back', pearls_path %>

app/views/pearls/index.html.erb
<h1>Listing pearls</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Parts</th>
      <th>Type</th>
      <th>Ep</th>
      <th>Effect</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pearls.each do |pearl| %>
      <tr>
        <td><%= pearl.title %></td>
        <td><%= pearl.parts %></td>
        <td><%= pearl.type %></td>
        <td><%= pearl.ep %></td>
        <td><%= pearl.effect %></td>
        <td><%= pearl.item %></td>
        <td><%= link_to 'Show', pearl %></td>
        <td><%= link_to 'Edit', edit_pearl_path(pearl) %></td>
        <td><%= link_to 'Destroy', pearl, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pearl', new_pearl_path %>

app/views/pearls/new.html.erb
<h1>New pearl</h1>

<%= render 'form' %>

<%= link_to 'Back', pearls_path %>

app/views/pearls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @pearl.title %>
</p>

<p>
  <strong>Parts:</strong>
  <%= @pearl.parts %>
</p>

<p>
  <strong>Type:</strong>
  <%= @pearl.type %>
</p>

<p>
  <strong>Ep:</strong>
  <%= @pearl.ep %>
</p>

<p>
  <strong>Effect:</strong>
  <%= @pearl.effect %>
</p>

<p>
  <strong>Item:</strong>
  <%= @pearl.item %>
</p>

<%= link_to 'Edit', edit_pearl_path(@pearl) %> |
<%= link_to 'Back', pearls_path %>