config/routes.rb
Rails.application.routes.draw do

  resources :magic_parts

  resources :pearls

  resources :battles

  get 'item/index'

  devise_for :users, :controllers => { registrations: 'registrations_' }
  get 'home/index'

  root 'home#index'
  post 'worlds/generate_new_area' => "worlds#generate_new_area"
  post 'worlds/claim_area' => "worlds#claim_area"
  post 'worlds/attack' => "worlds#attack"
  post 'battles/escape' => "battles#escape"
  post 'battles/join' => "battles#join"
  post 'worlds/search_location' => "worlds#search_location"
  post 'worlds/collect_world_item' => "worlds#collect_world_item"
  post 'worlds/teleport' => "worlds#get_teleport"
  get 'worlds/teleport' => "worlds#teleport"
  post 'item/item_action' => "item#item_action"
  resources :characters do
    resource :items
  end
  resources :worlds
  resources :guide
  resources :item
  resources :npc
  resources :lock
  resources :inventory do
    resources :items
  end

  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
  end

end

app/models/battle.rb
class Battle < ActiveRecord::Base
end

app/models/biome.rb
class Biome < ActiveRecord::Base
end

app/models/caves.rb
class Caves < ActiveRecord::Base
end

app/models/character.rb
class Character < ActiveRecord::Base
  validates_uniqueness_of :LastName
  belongs_to :user
  belongs_to :charclass
  belongs_to :race
  has_many :inventories
end

app/models/dungeons.rb
class Dungeons < ActiveRecord::Base
end

app/models/guide.rb
class Guide < ActiveRecord::Base
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  has_many :items, dependent: :destroy
  belongs_to :character
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :inventory
  has_many :inventories
  has_many :pearls
end

app/models/key.rb
class Key < ActiveRecord::Base
end

app/models/lock.rb
class Lock < ActiveRecord::Base
end

app/models/magic_part.rb
class MagicPart < ActiveRecord::Base
  self.inheritance_column = nil
end

app/models/material.rb
class Material < ActiveRecord::Base
end

app/models/npc.rb
class Npc < ActiveRecord::Base
end

app/models/pearl.rb
class Pearl < ActiveRecord::Base
  belongs_to :item
  self.inheritance_column = nil
end

app/models/trade.rb
class Trade < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :characters, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/world.rb
class World < ActiveRecord::Base
  validates :title, presence: true,
            length: { minimum: 5 }
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/npc_helper.rb
module NpcHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magiclord</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :javascripts %>
  <%= csrf_meta_tags %>
  <% #check_path %>
</head>
<body>
<div class="pure-menu pure-menu-open pure-menu-horizontal">
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Guide', guide_index_path %></li>
    <% if user_signed_in? %>
        <% if have_character %>
            <li><%= link_to 'Character', new_character_path %></li>
            <li><%= link_to 'World', worlds_path %></li>
            <li><%= link_to 'Inventory', item_index_path %></li>
            <li><%= link_to 'Crafting', new_item_path %></li>
            <li><a href="#">Quest</a></li>
        <% else %>
            <li><%= link_to 'Character', new_character_path %></li>
        <% end %>
        <% if current_user.try(:admin?) %>
            <li class="pure-menu-can-have-children pure-menu-has-children">
              <a href="#" data-toggle="dropdown">Admin<span class="pure-custom-caret"></span></a>
              <ul class="pure-menu-children">
                <li><a href="/worlds/new">New World</a></li>
                <li><a href="/npc/new">New NPC</a></li>
                <li><a href="/magic_parts/new">New Magic Parts</a></li>
                <li><a href="/worlds/teleport">Teleport</a></li>
              </ul>
            </li>
        <% end %>
        <li><%= link_to 'Logout', logout_path %></li>
    <% else %>
        <li><%= link_to 'Login', login_path %></li>
    <% end %>

  </ul>
</div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if user_signed_in?
     current_user
   end %>
<div class="pure-g">
  <div class="pure-u-1-3">
    <%= yield %>
  </div>
  <div class="pure-u-1-3">
    <h1>Console</h1>
    <div class="log" style="height:200px; border-style:solid; border-width:1px; overflow: scroll; font-size: 12px;">Log info that happens around the player</div>
    <input type="text" name="log" style="width:70%">
    <button style="width:20%">☺</button>
  </div>
  <% if user_signed_in? and have_character %>
      <div class="pure-u-1-3" id="stats_info">
        <% char = current_user.characters.where(Status: 1).first %>
        <h1><%= char.FirstName %></h1>
        <h2>Profile</h2>
        <p>Name: <%= char.FirstName.capitalize %> <%= char.LastName.capitalize %></p>
        <p>Age: <%= char.Age %></p>
        <p>Class: <%= char.Class.capitalize %></p>
        <p>Race: <%= char.Race.capitalize %></p>
        <p>Profession: <%= char.Primary_Profession.capitalize %>
          <% if !char.Secondary_Profession.nil? %>
             and <%= char.Secondary_Profession.capitalize %>
          <% end %>
        </p>
        <h2>Stats</h2>
        <p>Strength: <%= char.Strength %></p>
        <p>Agility: <%= char.Agility %></p>
        <p>Intelligence: <%= char.Intelligence %></p>
        <p>Stamina: <%= char.Stamina %></p>
        <h2>Condition</h2>
        <p>Health: <%= char.Curr_Hp %> / <%= max_health(char) %></p>
        <p>Stamina: <%= char.Curr_Stamina %> / <%= max_stamina(char) %></p>
        <h2>Buffs / Debuffs</h2>
        <% json = JSON.parse(char.effect) %>
        <% json.each do |effects| %>
            <% effects.each do |key, effect| %>
                <%= key %> do <%= effect["damage"] %> damage for <%= effect["turn"] %> more turns.
            <% end %>
        <% end %>
        <h2>Equipments</h2>
        <% inv = char.inventories.first %>
        <% inv.items.each do |item|%>
            <%= item.name %> (<%= item.equip %>)
            <% if item != inv.items.last %>
                <br/>
            <% end %>
        <% end %>
      </div>
  <% end %>
</div>
</body>
</html>